/* tslint:disable */
/* eslint-disable */
/**
 * socialApp API
 * generovani api pro soicalApp
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/auth-controller-api';

