/* tslint:disable */
/* eslint-disable */
/**
 * socialApp API
 * generovani api pro soicalApp
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import axios from "axios";


import * as Api from "./api";
export * from "./configuration";


const baseURL = "http://localhost:8000";

export const axiosInstance = axios.create({
     baseURL: baseURL,
     timeout: 0,
     headers: {'Content-Type': 'application/json'}
})

export const AuthApi = new Api.AuthControllerApi(undefined, baseURL, axiosInstance);